# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
    ldflags:
      - -X github.com/rsevilla87/kube-burner/version.GitCommit=${GIT_COMMIT}${GIT_DIRTY} -X github.com/rsevilla87/kube-burner/version.BuildDate=${BUILD_DATE}
archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
