docs_dir: docs/
repo_url: https://github.com/cloud-bulldozer/kube-burner
nav:
- Home:
  - Quick start: README.md
  - CLI: CLI.md
- Configuration: 
  - General: CONFIGURATION.md
  - Measurements: MEASUREMENTS.md
  - Metrics: METRICS.md
  - Indexers: INDEXERS.md
- Development:
  - Contributing: CONTRIBUTING.md
  - Authors: AUTHORS.md
site_name: Kube-burner
markdown_extensions:
- toc:
    permalink: "#"
theme:
  name: readthedocs
