---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-app-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kube-burner-{{ .Iteration }}-{{ .Replica }}
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: kube-burner-{{ .Iteration }}-{{ .Replica }}
    spec:
      containers:
      - args:
        - sleep
        - infinity
        image: quay.io/rsevilla/debug:latest
        name: kube-burner
        resources: {}
