---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-app-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleep-app-{{ .Iteration }}-{{ .Replica }}
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: sleep-app-{{ .Iteration }}-{{ .Replica }}
    spec:
      containers:
      - args:
        - sleep
        - infinity
        image: quay.io/rsevilla/debug:latest
        ports:
         - containerPort: {{ .containerPort }}
           protocol: TCP
        name: sleep-app
        resources: {}
