name: CI Parallel Tests
# Only run when called from another workflow
on:
  workflow_call:
    inputs:
      k8s-version:
        required: true
        type: string
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group:
          - "churn"
          - "gc"
          - "indexing"
          - "kubeconfig"
          - "kubevirt"
          - "alert"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      
      - name: Download kube-burner binary
        uses: actions/download-artifact@v4
        with:
          name: kube-burner
          path: /tmp/
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq podman uuid-runtime
          
      - name: Make binary executable
        run: chmod +x /tmp/kube-burner
        
      - name: Run bats tests for ${{ matrix.test-group }}
        run: make test-k8s TEST_FILTER="${{ matrix.test-group }}" TEST_BINARY=/tmp/kube-burner
        env:
          K8S_VERSION: ${{ inputs.k8s-version }}
          CI_MODE: "true"
