name: CI Parallel Tests
on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'test/**'
      - 'pkg/**'
      - 'cmd/**'
      - 'Makefile'
      - '.github/workflows/ci-parallel.yml'
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'test/**'
      - 'pkg/**'
      - 'cmd/**'
      - 'Makefile'
      - '.github/workflows/ci-parallel.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group:
          - "churn"
          - "gc"
          - "indexing"
          - "kubeconfig"
          - "kubevirt"
          - "alert"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq podman
      - name: Build kube-burner
        run: make build
      - name: Run bats tests for ${{ matrix.test-group }}
        run: make test-k8s TEST_FILTER="${{ matrix.test-group }}"
